#!/usr/bin/env bash
#
# BETR scoring pipeline for FineWeb parquet data.
#
# This script:
#   - Loads benchmark embeddings (generated by data/embed_benchmarks.py)
#   - Uses Arctic-Embed L v2 to embed FineWeb documents
#   - Writes scored parquet files with an extra 'betr_score' column
#
# Prerequisites:
#   1. Generate benchmark embeddings first:
#      python -u data/embed_benchmarks.py \
#        --data_dir opencompass/data \
#        --encoder_model Snowflake/snowflake-arctic-embed-l-v2.0 \
#        --output benchmark_embeddings_arctic_l_v2.npz

set -euo pipefail

# Auto-detect project root from this script's location
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-max_split_size_mb:128}"

# ======================= User-configurable paths ============================

# Input: FineWeb parquet tree (set these to your own paths)
INPUT_ROOT="${INPUT_ROOT:?'Set INPUT_ROOT to your FineWeb parquet directory'}"

# Output: BETR-scored parquet tree (same layout, extra 'betr_score' column)
OUTPUT_ROOT="${OUTPUT_ROOT:?'Set OUTPUT_ROOT for scored parquet output'}"

# Benchmark embeddings (generated by data/embed_benchmarks.py)
BENCHMARK_NPZ="${BENCHMARK_NPZ:-$ROOT_DIR/benchmark_embeddings_arctic_l_v2.npz}"

# Encoder model: HuggingFace name or local path
ENCODER_MODEL="${ENCODER_MODEL:-Snowflake/snowflake-arctic-embed-l-v2.0}"

# ======================= Compute / precision settings ======================

BATCH_SIZE="${BATCH_SIZE:-192}"
MAX_LENGTH="${MAX_LENGTH:-512}"
DTYPE="${DTYPE:-bfloat16}"
DEVICE="${DEVICE:-cuda}"

# Multi-GPU sharding (AUTO_MULTIGPU=1 + GPU_LIST=0,1,2,... to fan out automatically)
NUM_SHARDS="${NUM_SHARDS:-1}"
SHARD_IDX="${SHARD_IDX:-0}"
AUTO_MULTIGPU="${AUTO_MULTIGPU:-0}"
GPU_LIST="${GPU_LIST:-}"

# Optional: limit number of files processed (for testing)
MAX_FILES="${MAX_FILES:-}"

echo "============================================================"
echo "BETR Scoring for FineWeb Parquet"
echo "============================================================"
echo "Input root:      $INPUT_ROOT"
echo "Output root:     $OUTPUT_ROOT"
echo "Benchmark npz:   $BENCHMARK_NPZ"
echo "Encoder model:   $ENCODER_MODEL"
if [[ "$AUTO_MULTIGPU" == "1" ]]; then
  echo "CUDA devices:    (auto multi-GPU) ${GPU_LIST:-<not set>}"
else
  echo "CUDA devices:    ${CUDA_VISIBLE_DEVICES:-0}"
fi
echo "Batch size:      $BATCH_SIZE"
echo "Max length:      $MAX_LENGTH"
echo "Dtype:           $DTYPE"
echo "Device:          $DEVICE"
echo "Shards:          $NUM_SHARDS (this worker idx: $SHARD_IDX)"
if [[ -n "${MAX_FILES}" ]]; then
  echo "Max files:       $MAX_FILES (for testing)"
fi
echo "============================================================"
echo ""

build_base_cmd() {
  BASE_CMD=(python -u data/betr_score_parquet.py
    --input_root "$INPUT_ROOT"
    --output_root "$OUTPUT_ROOT"
    --benchmark_npz "$BENCHMARK_NPZ"
    --encoder_model "$ENCODER_MODEL"
    --batch_size "$BATCH_SIZE"
    --max_length "$MAX_LENGTH"
    --device "$DEVICE"
    --dtype "$DTYPE"
    --num_shards "$NUM_SHARDS")

if [[ -n "${MAX_FILES}" ]]; then
    BASE_CMD+=(--max_files "$MAX_FILES")
  fi
}

build_base_cmd

run_worker() {
  local gpu_id="$1"
  local shard_idx="$2"
  local label="$3"
  local cmd=( "${BASE_CMD[@]}" --shard_idx "$shard_idx" )
  echo ">>> Launching shard $shard_idx on GPU $gpu_id ($label)"
  echo "    Command: ${cmd[*]}"
  CUDA_VISIBLE_DEVICES="$gpu_id" "${cmd[@]}"
}

if [[ "$AUTO_MULTIGPU" == "1" ]]; then
  if [[ -z "$GPU_LIST" ]]; then
    echo "AUTO_MULTIGPU=1 but GPU_LIST is empty. Please set GPU_LIST (e.g., GPU_LIST=0,1,2,3)."
    exit 1
  fi
  IFS=',' read -r -a GPU_ARRAY <<< "$GPU_LIST"
  if [[ "${#GPU_ARRAY[@]}" -eq 0 ]]; then
    echo "GPU_LIST parsed to zero GPUs. Check format (comma-separated, no spaces)."
    exit 1
  fi
  if [[ "$NUM_SHARDS" -ne "${#GPU_ARRAY[@]}" ]]; then
    echo "Adjusting NUM_SHARDS to match GPU count (${#GPU_ARRAY[@]})."
    NUM_SHARDS="${#GPU_ARRAY[@]}"
    build_base_cmd
  fi
  for idx in "${!GPU_ARRAY[@]}"; do
    gpu="${GPU_ARRAY[$idx]}"
    (
      run_worker "$gpu" "$idx" "auto-multi"
    ) &
  done
  wait
else
  run_worker "${CUDA_VISIBLE_DEVICES:-0}" "$SHARD_IDX" "single-run"
fi

echo ""
echo "============================================================"
echo "BETR scoring complete."
echo "Scored parquet files are under: $OUTPUT_ROOT"
echo "Each file now has a 'betr_score' column."
echo "============================================================"
